name: Deploy to NuGet

on:
  push:
    branches: [ main ]
    paths: [ 'BlazorScheduler/**' ]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Publish NuGet
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: BlazorScheduler/BlazorScheduler.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
